### ISSUE TITLE
Cannot read properties of undefined (reading 'usdPrice')

### ISSUE THREAD

**Issue by OliverNChalk** [vexchange/governance-frontend#31]
### How I triggered the issue

Attempted to open the asset tab on gov.vexchange.io, fairly quickly after the page loaded (or was still loading). This triggered an exception to be thrown and the page to crash.

### Details

Screenshot:
![image](https://user-images.githubusercontent.com/11343499/153329085-7de79ec8-d69e-4ec8-a24a-d7920ae0ae3f.png)

My intuition is that attempting to open the asset page to quickly causes this. I.e. there are some resources that have not been loaded and thus are undefined when the page change is triggered.

**Comment by xenide** [comment]
Fixed by Kenneth in https://github.com/vexchange/governance-frontend/commit/330e71e7c66f620ba23704bbc9a77fc9f935845e


Closing
